// Code generated by "stringer -type=Leaf"; DO NOT EDIT.

package regx

import "strconv"

const _Leaf_name = "ADDRCMNTDESCDSBLFLIPFQDNHOSTHTTPIPBHLEAFLBRCMISCMLTIMPTYNAMENODERBRCSUFX"

var _Leaf_index = [...]uint8{0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72}

func (i Leaf) String() string {
	i -= 1000
	if i < 0 || i >= Leaf(len(_Leaf_index)-1) {
		return "Leaf(" + strconv.FormatInt(int64(i+1000), 10) + ")"
	}
	return _Leaf_name[_Leaf_index[i]:_Leaf_index[i+1]]
}
