// generated by stringer -type=ntype; DO NOT EDIT

package edgeos

import "fmt"

const ntypeName = "unknowndomainexcDomnexcHostexcRoothostpreDomnpreHostrootzone"

var ntypeIndex = [...]uint8{7, 13, 20, 27, 34, 38, 45, 52, 56, 60}

func (i ntype) String() string {
	if i < 0 || i >= ntype(len(ntypeIndex)) {
		return fmt.Sprintf("ntype(%d)", i)
	}
	hi := ntypeIndex[i]
	lo := uint8(0)
	if i > 0 {
		lo = ntypeIndex[i-1]
	}
	return ntypeName[lo:hi]
}
