// generated by stringer -type=ntype; DO NOT EDIT

package edgeos

/* Generated by stringer */

import "fmt"

const ntypeName = "unknownpredomainhostrootzone"

var ntypeIndex = [...]uint8{7, 10, 16, 20, 24, 28}

func (i ntype) String() string {
	if i < 0 || i >= ntype(len(ntypeIndex)) {
		return fmt.Sprintf("ntype(%d)", i)
	}
	hi := ntypeIndex[i]
	lo := uint8(0)
	if i > 0 {
		lo = ntypeIndex[i-1]
	}
	return ntypeName[lo:hi]
}
