// generated by stringer -type=ntype; DO NOT EDIT

package edgeos

import "fmt"

const _ntype_name = "unknowndomainhostpreDomnpreHostrootzone"

var _ntype_index = [...]uint8{7, 13, 17, 24, 31, 35, 39}

func (i ntype) String() string {
	if i < 0 || i >= ntype(len(_ntype_index)) {
		return fmt.Sprintf("ntype(%d)", i)
	}
	hi := _ntype_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _ntype_index[i-1]
	}
	return _ntype_name[lo:hi]
}
